### ISSUE TITLE
Cannot find all of the three losses mentioned in the paper

### ISSUE THREAD

**Issue by HabibAouani** [kurtisdavid/MetaOrthogonalization#1]
Hello Kurtis;
I hope you're doing well.

Could you please help me, finding, all of the losses below (mentioned in the paper):
- L_debias
- L_concept
- L_class

I'm trying to reproduce the algorithm.
Thank you very much,
Habib

**Comment by kurtisdavid** [comment]
Hi Habib, 

I apologize for the delayed response. References of each can be found in `debias_train.py`. Specifically:

- L_debias: `debias.debias_loss` (i.e. check `debias.py` as well)
- L_concept: `prelim_loss` (lines 535-537 for examples. Refer to `balanced_loss` in `utils.py` as well.
- L_class: `class_loss` (line 557)

Please let me know if you'd like additional clarifications,
Kurtis
